### ISSUE TITLE
salmon options for terminus

### ISSUE THREAD

**Issue by JennyFrodoBrynnNick** [COMBINE-lab/Terminus#11]
Hi, in the Terminus documentation it is stated that Salmon should be run with -la and -d. I cannot find these two options anywhere in the Salmon documentation!? I ran Salmon instead with -l A and --dumpEqn (and --gcBias) but this produced an error with Terminus. Are -d and --dumpEq not equivalent, and what is -la?
Thank you.

**Comment by jonahcullen** [comment]
Hello, I was wondering what the answer was re: -la? I cannot seem to find it in the salmon documentation either.

**Comment by jonahcullen** [comment]
> Hi, in the Terminus documentation it is stated that Salmon should be run with -la and -d. I cannot find these two options anywhere in the Salmon documentation!? I ran Salmon instead with -l A and --dumpEqn (and --gcBias) but this produced an error with Terminus. Are -d and --dumpEq not equivalent, and what is -la?
> Thank you.
