### ISSUE TITLE
collapse error

### ISSUE THREAD

**Issue by kcamnairb** [COMBINE-lab/Terminus#14]
Hi,

I'm getting an error when running terminus collapse indicating it can't find a file: `thread "main" panicked at "called Result::unwrap() on an Err value: Os { code: 2, kind: NotFound, message: "No such file or directory" }, src/util.rs:267:38`
Here is the way I've run group and collapse:
`parallel -j 72 terminus group --dir {} --min-spread 0.05 --tolerance 0.01 --out output/terminus_group ::: output/salmon/*`
`terminus collapse -t 1 -c 0.5 -d output/terminus_group/* -o output/terminus_collapse`
Am I missing something? I'm running Terminus 0.1.0.

Thanks,
Brian

**Comment by NPSDC** [comment]
Hi Brian,
The input and output that you provide for `collapse` are incorrect. The `-d` should be the salmon quantified directories and `-o` should be the same as the output of `group` flag.

Assuming folders in `salmon` directory are `quant1`, `quant2` ... `quant72`, then run `collaspe` as following:
`terminus collapse -t 1 -c 0.5 -d output/salmon/quant1 output/salmon/quant2 ... output/salmon/quant72  -o output/terminus_group`

**Comment by kcamnairb** [comment]
Thank you. That worked for me.
